'use strict';
(() => {
 const API='https://yobymeygbfiwlngmwjcn.supabase.co/functions/v1/retail-control';
 const LIFF_ID='2011681452-k1lfYGsF';
 const $=id=>document.getElementById(id);
 const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=c=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB'}).format(Number(c)/100);
 const number=n=>new Intl.NumberFormat('en-US',{minimumIntegerDigits:2}).format(Number(n));
 const day=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const channelNames={store:'หน้าร้าน',line:'LINE',facebook:'Facebook',tiktok:'TikTok',shopee:'Shopee',website:'เว็บไซต์',other:'อื่น ๆ'};
 const errors={invalid_line_login:'การเข้าสู่ระบบหมดอายุ กรุณาเข้าสู่ระบบ LINE อีกครั้ง',staff_access_required:'บัญชีนี้ยังไม่มีสิทธิ์ กรุณาส่งรหัสบัญชีให้เจ้าของร้านเพิ่มทีม',owner_required:'รายการนี้สำหรับเจ้าของร้าน',insufficient_stock:'สต๊อกไม่พอ มีคนขายรายการนี้แล้ว กรุณาตรวจจำนวนใหม่',request_conflict:'รหัสรายการนี้ถูกใช้แล้ว กรุณาตรวจรายการเดิม',duplicate_sku:'SKU นี้มีอยู่แล้ว',product_not_found:'ไม่พบสินค้านี้',stock_limit:'จำนวนเกินขีดจำกัด',invalid_transaction:'กรุณาตรวจจำนวน ราคา และช่องทางขาย',retail_unavailable:'ระบบยังไม่พร้อม กรุณาลองใหม่',invalid_product:'กรุณาตรวจข้อมูลสินค้า',invalid_staff:'กรุณาตรวจชื่อและรหัสบัญชี LINE'};
 let products=[],authorized=false,owner=false,actor='',page='home',filter='all',selection=null,pending=null,busy=false,epoch=0,report=null,snapshotBusy=false,toastTimer;
 const storage={get:k=>{try{return sessionStorage.getItem(k)}catch{return null}},set:(k,v)=>{try{sessionStorage.setItem(k,v)}catch{}},remove:k=>{try{sessionStorage.removeItem(k)}catch{}}};
 const key=()=>`chaylueklab.retail.pending.${actor}`;
 function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3200)}
 function showError(id,message){$(id).hidden=!message;$(id).textContent=message||''}
 function connection(title,message,login=false){$('connection').hidden=false;$('connectionTitle').textContent=title;$('connectionText').textContent=message;$('login').hidden=!login}
 function cents(value){if(!/^\d+(\.\d{1,2})?$/.test(String(value)))throw new Error('ราคาใช้ทศนิยมได้ไม่เกิน 2 ตำแหน่ง');const [a,b='']=String(value).split('.');const n=Number(a)*100+Number(b.padEnd(2,'0'));if(!Number.isSafeInteger(n)||n>100000000)throw new Error('กรุณาตรวจราคา');return n}
 async function request(body){
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);
  try{
   const auth={idToken:window.liff?.getIDToken()||null,accessToken:window.liff?.getAccessToken()||null};
   const response=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,...auth}),signal:controller.signal});
   let data;try{data=await response.json()}catch{throw Object.assign(new Error('ยังตรวจผลไม่ได้ กรุณาตรวจรายการเดิมอีกครั้ง'),{uncertain:true})}
   if(!response.ok||!data.ok){const error=Object.assign(new Error(errors[data.error]||'บันทึกไม่สำเร็จ กรุณาลองใหม่'),{code:data.error,status:response.status,uncertain:response.status>=500});if(data.lineUserId){actor=data.lineUserId;$('copyIdentity').hidden=false}throw error}
   return data;
  }catch(e){if(e.name==='AbortError'||e instanceof TypeError)throw Object.assign(new Error('การเชื่อมต่อขาดหาย กรุณาตรวจรายการเดิมก่อนทำรายการใหม่'),{uncertain:true});throw e}finally{clearTimeout(timer)}
 }
 function renderProducts(){
  const search=$('search').value.toLocaleLowerCase();
  const items=products.filter(p=>(!search||[p.name,p.variant,p.sku].join(' ').toLocaleLowerCase().includes(search))&&(filter==='all'||(filter==='out'?p.quantity===0:p.quantity>0&&p.quantity<=p.low_threshold)));
  $('products').innerHTML=items.length?items.map(p=>{
   const state=p.quantity===0?'out':p.quantity<=p.low_threshold?'low':'ready';
   return `<article class="product-card ${state}${selection?.id===p.id?' selected':''}" data-product="${p.id}"><div class="product-heading"><h3>${escape(p.name)}</h3><span class="variant">${escape(p.variant||p.sku)}</span></div><strong class="stock-number">${number(p.quantity)}</strong><p class="stock-status">${{ready:'IN STOCK',low:'LOW STOCK',out:'OUT OF STOCK'}[state]}</p><span class="product-price">${money(p.price_cents)}</span><div class="product-actions"><button data-sell="${p.id}" ${p.quantity===0||!authorized||pending?'disabled':''}>ขายออก</button><button data-receive="${p.id}" ${!authorized||pending?'disabled':''}>รับเข้า</button></div></article>`;
  }).join(''):`<div class="empty"><span class="empty-mark">C / L</span><h3>${authorized?(products.length?'ไม่พบสินค้าที่ค้นหา':'ยังไม่มีสินค้า'):'สต๊อกกลางของทีม'}</h3><p>${authorized?(owner?'กดเพิ่มสินค้า แล้วรับจำนวนจริงเข้าสต๊อก':'ให้เจ้าของร้านเพิ่มสินค้าก่อนเริ่มขาย'):'เข้าสู่ระบบเพื่อดูจำนวนจริง'}</p></div>`;
 }
 function metric(id,value){const el=$(id);if(el.textContent!==number(value)){el.textContent=number(value);el.classList.remove('number-change');void el.offsetWidth;el.classList.add('number-change')}}
 async function loadSnapshot(quiet=false){
  if(!window.liff?.isLoggedIn()||busy||snapshotBusy)return;
  snapshotBusy=true;const version=++epoch;$('syncLabel').textContent='กำลังอัปเดต';
  try{
   const data=await request({action:'snapshot',day:day()});if(version!==epoch)return;
   actor=data.lineUserId;owner=data.owner;authorized=true;products=data.products;
   $('connection').hidden=true;$('copyIdentity').hidden=true;$('addProduct').hidden=!owner;$('team').hidden=!owner;
   for(const id of ['sold','remaining','low','out'])metric(id,data.stats[id]);
   $('syncLabel').textContent='อัปเดต '+new Date().toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'});
   if(!pending){try{const saved=JSON.parse(storage.get(key())||'null');if(saved?.actor===actor&&saved?.body?.action==='transact')pending=saved}catch{storage.remove(key())}}
   $('pendingBanner').hidden=!pending;renderProducts();
   if($('reportDate').value===data.day){report=data;renderReport()}
   if(page==='reports'&&$('reportDate').value!==data.day)await loadReport();
  }catch(e){if(version!==epoch)return;$('syncLabel').textContent='ยังอัปเดตไม่ได้';if(e.status===401||e.status===403){authorized=false;products=[];owner=false;$('team').hidden=true;$('addProduct').hidden=true;report=null;$('channels').replaceChildren();$('history').replaceChildren();$('staffList').replaceChildren();$('revenue').textContent='—';for(const id of ['sold','remaining','low','out'])$(id).textContent='—';renderProducts();connection('ตรวจสิทธิ์บัญชี',e.message,e.status===401)}else if(!quiet)connection('เชื่อมต่อไม่สำเร็จ',e.message,false)}finally{snapshotBusy=false;if(version!==epoch&&!busy)queueMicrotask(()=>loadSnapshot(true))}
 }
 function navigate(next){page=next;document.querySelector('.hero').hidden=next!=='home';$('pageTitle').textContent=({home:'ระบบหลังร้าน',sale:'ขายสินค้า',receive:'รับสินค้าเข้า',stock:'สต๊อกกลาง',reports:'รายงาน'})[next];$('quick').hidden=next!=='home';$('catalog').hidden=next==='reports';$('reports').hidden=next!=='reports';$('catalogTitle').textContent=next==='sale'?'เลือกสินค้าที่ต้องการขาย':next==='receive'?'เลือกสินค้าที่รับเข้า':'สต๊อกของร้าน';document.querySelectorAll('.bottom-nav [data-go]').forEach(b=>{if(b.dataset.go===next)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});if(next==='reports'&&authorized)loadReport();window.scrollTo({top:0,behavior:'instant'})}
 function openTransaction(id,kind){
  if(!authorized)return toast('เข้าสู่ระบบ LINE ก่อนทำรายการ');if(pending)return recover();
  selection=products.find(p=>p.id===id);if(!selection)return;selection={...selection,kind};
  $('transactionForm').reset();$('quantity').value=1;$('salePrice').value=(selection.price_cents/100).toFixed(2);$('saleFields').hidden=kind==='receive';$('salePrice').required=kind==='sale';$('selectedName').textContent=selection.name;$('selectedVariant').textContent=selection.variant||selection.sku;$('selectedStock').textContent=number(selection.quantity);$('transactionLabel').textContent=kind==='sale'?'SELL PRODUCT':'RECEIVE STOCK';$('transactionTitle').textContent=kind==='sale'?'ขายสินค้า':'รับสินค้าเข้า';$('confirm').textContent=kind==='sale'?'ยืนยันขาย':'ยืนยันรับเข้า';setTransactionBusy(false);showError('transactionError','');renderProducts();updateTotal();$('transactionDialog').showModal();
 }
 function updateTotal(){try{$('saleTotal').textContent='รวม '+money(cents($('salePrice').value)*Number($('quantity').value))}catch{$('saleTotal').textContent='กรุณาตรวจราคา'}}
 function setTransactionBusy(locked){for(const el of $('transactionForm').elements)if(!el.hasAttribute('data-close'))el.disabled=locked;$('confirm').disabled=busy;$('confirm').textContent=busy?'กำลังตรวจและบันทึก…':pending?'ตรวจรายการเดิมอีกครั้ง':selection?.kind==='receive'?'ยืนยันรับเข้า':'ยืนยันขาย'}
 function clearPending(){storage.remove(key());pending=null;$('pendingBanner').hidden=true;setTransactionBusy(false)}
 async function sendPending(){
  if(busy||!pending)return;busy=true;++epoch;setTransactionBusy(true);showError('transactionError','');
  try{
   const result=await request(pending.body);const kind=pending.body.kind;clearPending();if(!result.replayed){const p=products.find(p=>p.id===result.transaction.product_id);if(p)p.quantity=result.transaction.stock_after}renderProducts();$('transactionDialog').close();toast(result.replayed?'รายการเดิมบันทึกแล้ว':kind==='sale'?'✓ ขายเรียบร้อย':'✓ รับสินค้าเรียบร้อย');
  }catch(e){
   if(!e.uncertain&&e.status!==401&&e.status!==403)clearPending();
   showError('transactionError',e.message);$('pendingBanner').hidden=!pending;toast(e.message);
  }finally{busy=false;setTransactionBusy(!!pending);renderProducts();await loadSnapshot(true)}
 }
 function recover(){if(!pending)return;selection={...(products.find(p=>p.id===pending.body.productId)||{}),kind:pending.body.kind};$('selectedName').textContent=selection.name||'รายการเดิม';$('selectedVariant').textContent=selection.variant||'';$('selectedStock').textContent=selection.quantity==null?'—':number(selection.quantity);$('quantity').value=pending.body.quantity;$('salePrice').value=(pending.body.priceCents/100).toFixed(2);$('note').value=pending.body.note;$('saleFields').hidden=pending.body.kind==='receive';document.querySelectorAll('[name="channel"]').forEach(el=>el.checked=el.value===pending.body.channel);$('transactionTitle').textContent='ตรวจรายการเดิม';$('transactionLabel').textContent='PENDING TRANSACTION';updateTotal();setTransactionBusy(true);showError('transactionError','ตรวจซ้ำด้วยรหัสรายการเดิม ระบบจะไม่ตัดสต๊อกซ้ำ');if(!$('transactionDialog').open)$('transactionDialog').showModal()}
 async function loadReport(){if(!authorized)return;const requested=$('reportDate').value;$('reportSummary').textContent='กำลังโหลดรายงาน…';try{const data=await request({action:'snapshot',day:requested});if(requested!==$('reportDate').value)return;report=data;renderReport()}catch(e){report=null;$('revenue').textContent='—';$('channels').replaceChildren();$('history').replaceChildren();$('reportSummary').textContent=e.message}}
 function renderReport(){if(!report)return;$('revenue').textContent=money(report.stats.revenue_cents);$('reportSummary').textContent=`ขาย ${number(report.stats.sold)} ชิ้น · รับเข้า ${number(report.stats.received)} ชิ้น · ${report.day}`;$('channels').innerHTML=report.channels.length?report.channels.map(c=>`<div class="channel-row"><span>${escape(channelNames[c.channel]||c.channel)}</span><span>${number(c.units)} ชิ้น</span><strong>${money(c.revenue_cents)}</strong></div>`).join(''):'<p class="caption">ยังไม่มีการขายในวันที่เลือก</p>';$('history').innerHTML=report.recent.length?report.recent.map(t=>`<article class="history-row"><div><h4>${escape(t.name)} ${escape(t.variant)}</h4><span>${t.kind==='sale'?'ขาย':'รับเข้า'} · ${escape(channelNames[t.channel])} · ${new Date(t.created_at).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'})}</span>${t.note?`<p>${escape(t.note)}</p>`:''}</div><strong>${t.kind==='sale'?'−':'＋'}${number(t.quantity)}</strong></article>`).join(''):'<p class="caption">ยังไม่มีรายการ</p>'}
 async function staffList(){if(!owner)return;try{const data=await request({action:'staff_list'});$('staffList').innerHTML=data.staff.map(s=>`<div class="staff-row"><span>${escape(s.display_name)}<small>${s.active?'เปิดสิทธิ์':'ปิดสิทธิ์'}</small></span><button class="text-button" data-staff="${s.line_user_id}" data-name="${escape(s.display_name)}" data-active="${!s.active}">${s.active?'ปิดสิทธิ์':'เปิดสิทธิ์'}</button></div>`).join('')}catch(e){toast(e.message)}}
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.go)navigate(b.dataset.go);if(b.dataset.filter){filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));renderProducts()}if(b.dataset.sell)openTransaction(b.dataset.sell,'sale');if(b.dataset.receive)openTransaction(b.dataset.receive,'receive');if(b.hasAttribute('data-close'))b.closest('dialog').close();if(b.dataset.staff){b.disabled=true;request({action:'staff_save',lineUserId:b.dataset.staff,displayName:b.dataset.name,active:b.dataset.active==='true'}).then(staffList).catch(e=>toast(e.message)).finally(()=>b.disabled=false)}});
 $('search').addEventListener('input',renderProducts);$('refresh').onclick=()=>loadSnapshot();$('recover').onclick=recover;
 $('quantity').oninput=updateTotal;$('salePrice').oninput=updateTotal;for(const [id,delta] of [['decrease',-1],['increase',1]])$(id).onclick=()=>{$('quantity').value=Math.max(1,Math.min(100000,Number($('quantity').value)+delta));updateTotal()};
 $('transactionDialog').addEventListener('close',()=>{if(!pending){selection=null;renderProducts()}});
 $('transactionForm').onsubmit=e=>{e.preventDefault();if(busy)return;if(pending)return sendPending();try{const quantity=Number($('quantity').value);if(!selection||!Number.isInteger(quantity)||quantity<1||quantity>100000)throw new Error('กรุณาตรวจจำนวน');if(selection.kind==='sale'&&quantity>selection.quantity)throw new Error('จำนวนมากกว่าสต๊อกที่มี');pending={actor,body:{action:'transact',requestId:crypto.randomUUID(),productId:selection.id,kind:selection.kind,quantity,priceCents:selection.kind==='sale'?cents($('salePrice').value):0,channel:selection.kind==='sale'?$('transactionForm').elements.channel.value:'store',note:$('note').value.trim()}};storage.set(key(),JSON.stringify(pending));$('pendingBanner').hidden=false;sendPending()}catch(error){showError('transactionError',error.message)}};
 $('addProduct').onclick=()=>{$('productForm').reset();showError('productError','');$('productDialog').showModal()};
 $('productForm').onsubmit=async e=>{e.preventDefault();const form=e.target,button=form.querySelector('.primary');if(button.disabled)return;button.disabled=true;try{const f=new FormData(form);const data=await request({action:'create_product',name:f.get('name'),variant:f.get('variant'),sku:f.get('sku'),priceCents:cents(f.get('price')),lowThreshold:Number(f.get('threshold'))});$('productDialog').close();toast('เพิ่มสินค้าแล้ว กรุณารับจำนวนเข้าสต๊อก');await loadSnapshot();openTransaction(data.product.id,'receive')}catch(error){showError('productError',error.message)}finally{button.disabled=false}};
 $('team').addEventListener('toggle',()=>{if($('team').open)staffList()});$('staffForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');if(button.disabled)return;button.disabled=true;try{const f=new FormData(e.target);await request({action:'staff_save',lineUserId:f.get('lineUserId'),displayName:f.get('displayName'),active:true});e.target.reset();await staffList();toast('เปิดสิทธิ์พนักงานแล้ว')}catch(error){toast(error.message)}finally{button.disabled=false}};
 $('reportDate').value=day();$('reportDate').onchange=loadReport;
 $('export').onclick=()=>{if(!report)return toast('โหลดรายงานก่อน');const cell=v=>'"'+String(/^[=+\-@\t\r]/.test(String(v))?'\''+v:v).replace(/"/g,'""')+'"';const rows=[['รายงานวันที่',report.day],['ขาย (ชิ้น)',report.stats.sold],['ยอดขาย (บาท)',report.stats.revenue_cents/100],[],['50 รายการล่าสุด (ทุกวัน)'],['วันเวลา','สินค้า','ไซซ์','SKU','ประเภท','ช่องทาง','จำนวน','ราคาต่อชิ้น (บาท)','หมายเหตุ'],...report.recent.map(t=>[t.created_at,t.name,t.variant,t.sku,t.kind,channelNames[t.channel],t.quantity,t.price_cents/100,t.note])];const blob=new Blob(['\ufeff'+rows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`CHAYLUEKLAB-${report.day}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 $('copyIdentity').onclick=async()=>{try{await navigator.clipboard.writeText(actor);toast('คัดลอกรหัสบัญชีแล้ว')}catch{$('connectionText').textContent='ส่งรหัสนี้ให้เจ้าของร้าน: '+actor}};
 $('login').onclick=async()=>{try{await window.liff.init({liffId:LIFF_ID});if(window.liff.isLoggedIn())await loadSnapshot();else window.liff.login({redirectUri:location.href})}catch{connection('เชื่อมต่อ LINE ไม่สำเร็จ','กรุณาเปิดผ่าน LINE หรือลองใหม่',true)}};
 async function start(){try{if(!window.liff)throw new Error();await window.liff.init({liffId:LIFF_ID});if(window.liff.isLoggedIn())await loadSnapshot();else connection('เชื่อมต่อทีมของคุณ','เข้าสู่ระบบ LINE เพื่อใช้สต๊อกกลางของ CHAYLUEKLAB',true)}catch{connection('เชื่อมต่อ LINE ไม่สำเร็จ','กรุณาตรวจอินเทอร์เน็ต แล้วกดเข้าสู่ระบบอีกครั้ง',true)}}
 document.addEventListener('visibilitychange',()=>{if(!document.hidden)loadSnapshot(true)});window.addEventListener('focus',()=>loadSnapshot(true));setInterval(()=>{if(!document.hidden)loadSnapshot(true)},15000);start();
})();
