
const names=["แนะนำอาชีพที่กำลังมาแรง","วิเคราะห์ทักษะและอาชีพเสริม","แผนขายออนไลน์ 30 วัน","10 วิธีหาเงินด้วยมือถือ","แผนสู่รายได้ 100,000 บาท","เขียนแคปชั่นขายสินค้า","ตั้งชื่อแบรนด์","วางแผนโพสต์ 7 วัน","คิดโปรโมชัน","สคริปต์ไลฟ์ขายสินค้า","โครง eBook","หัวข้อคอร์สออนไลน์","ตั้งชื่อคอร์ส","ออกแบบของแจก Lead Magnet","คอนเทนต์ขาย eBook","เปลี่ยนความรู้เป็นสินค้า","สรุปไลฟ์เป็นโพสต์","ประสบการณ์เป็นคอนเทนต์","แพ็กเกจให้คำปรึกษา","ตั้งราคาสินค้าความรู้"];
const groups=["เริ่มหาเงิน","AI SELLER","สินค้าดิจิทัล","เปลี่ยนความรู้เป็นเงิน"];
const seller=new Set([5,6,7,8,9]);
const grid=document.querySelector("#grid"),sel=document.querySelector("#tool"),out=document.querySelector("#output");
names.forEach((name,i)=>{const active=seller.has(i),card=document.createElement("article");card.className="card";const h=document.createElement("h3");h.textContent=(i+1)+". "+name;const p=document.createElement("p");p.textContent=groups[Math.floor(i/5)]+" · "+(active?"ทดลองได้":"เร็ว ๆ นี้");const b=document.createElement("button");b.textContent=active?"ทดลองเครื่องมือ":"รอเปิดใช้";b.disabled=!active;b.onclick=()=>{sel.value=i;document.querySelector("#workspace").scrollIntoView({behavior:"smooth"})};card.append(h,p,b);grid.append(card);if(active){const o=document.createElement("option");o.value=i;o.textContent=name;sel.append(o)}});
function generate(i,product,audience,detail){const a=audience||"ลูกค้าทั่วไป",d=detail||"คุณภาพและบริการที่ดี";switch(i){
case 5:return ["แคปชั่น 1: "+product+" ที่ตอบโจทย์ "+a+" ✨","จุดเด่น: "+d,"สนใจรายละเอียดเพิ่มเติม? ทักแชตเพื่อสอบถามได้เลย","#"+product.replace(/\s/g,"")+" #CHAYLUEKLAB"].join("\n");
case 6:return ["แนวคิดชื่อแบรนด์สำหรับ "+product,"1. "+product+" Studio","2. "+product+" Select","3. "+product+" Everyday","4. "+product+" Lab","5. "+product+" Collective","ตรวจสอบชื่อซ้ำ เครื่องหมายการค้า และโดเมนก่อนใช้จริง"].join("\n");
case 7:return Array.from({length:7},(_,n)=>"วันที่ "+(n+1)+": "+["แนะนำสินค้าและเรื่องราว","ปัญหาที่ลูกค้าพบ","จุดเด่นสินค้า","เบื้องหลังและความน่าเชื่อถือ","ตอบคำถามยอดนิยม","ตัวอย่างการใช้งานจริง","สรุปข้อเสนอและชวนทักแชต"][n]+" — "+product+" / "+a).join("\n");
case 8:return ["ไอเดียโปรโมชันสำหรับ "+product,"1. ซื้อคู่ราคาพิเศษ (คำนวณกำไรก่อน)","2. ของแถมสำหรับจำนวนจำกัด","3. ส่งฟรีเมื่อถึงยอดขั้นต่ำ","4. คูปองลูกค้าเก่า","5. โปรเฉพาะช่วงไลฟ์","ตรวจสอบต้นทุน กำไร และเงื่อนไขให้ชัดเจนก่อนประกาศ"].join("\n");
case 9:return ["[เปิดไลฟ์] สวัสดีครับ/ค่ะ วันนี้พามารู้จัก "+product,"[สร้างความสนใจ] เหมาะสำหรับ "+a,"[แนะนำ] จุดเด่นที่อยากเล่า: "+d,"[สาธิต] โชว์สินค้าและตอบคำถามตามจริง","[ปิดการขาย] ถ้าสนใจ พิมพ์สอบถามหรือกดดูรายละเอียดได้เลย ขอบคุณครับ/ค่ะ"].join("\n");
default:return ""}}
document.querySelector("#generate").onclick=()=>{const product=document.querySelector("#product").value.trim(),audience=document.querySelector("#audience").value.trim(),detail=document.querySelector("#detail").value.trim();if(!product){out.textContent="กรุณาระบุสินค้า / ธุรกิจ";return}out.textContent=generate(Number(sel.value),product,audience,detail);document.querySelector("#notice").textContent="ผลลัพธ์ตัวอย่างจากเทมเพลต ไม่ใช่ AI API และยังไม่หักเครดิต"};
document.querySelector("#copy").onclick=async()=>{try{await navigator.clipboard.writeText(out.textContent);document.querySelector("#notice").textContent="คัดลอกแล้ว"}catch{document.querySelector("#notice").textContent="เลือกข้อความผลลัพธ์แล้วคัดลอกด้วยตนเอง"}};
